// The changelog in README.md is where versions are made: its first entry,
// "* vYYYY.MM.N" under "## Changelog", is the current version.
//
//   node scripts/changelog.mjs --write    config/version.generated.js (dev, build)
//   node scripts/changelog.mjs --github   GitHub Actions outputs for release.yml
//
// A version is released when its tag v<version> exists. package.json cannot
// have leading zeros, so v2026.09.5 is 2026.9.5 there.
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

const PACKAGE = "kubesec-diagram";
const ROOT = path.resolve(import.meta.dirname, "..");
const README = path.join(ROOT, "README.md");
const MODULE = path.join(ROOT, "config", "version.generated.js");
const HEADING = /^## Changelog\s*$/;
const ENTRY = /^\* v(\d{4})\.(\d{2})\.(\d+)\s*$/;
const TAG = /^refs\/tags\/v(\d{4})\.(\d{2})\.(\d+)$/;
const NOTE = /^\s+\S/;

function parseChangelog(markdown) {
  const lines = markdown.split("\n");
  const start = lines.findIndex((line) => HEADING.test(line));
  if (start === -1) throw new Error("README.md: no '## Changelog' heading");
  const entries = [];
  let entry = null;
  for (const line of lines.slice(start + 1)) {
    if (line.startsWith("## ")) break;
    if (line.startsWith("* ")) {
      const match = ENTRY.exec(line);
      // Entries from before CalVer (* v11 (2026-03-04)) are history; the top one must be CalVer.
      if (!match && entries.length === 0) throw new Error(`README.md changelog: the first entry "${line.trim()}" is not "* vYYYY.MM.N"`);
      if (!match) {
        entry = null;
        continue;
      }
      const [year, month, serial] = match.slice(1).map(Number);
      if (month < 1 || month > 12) throw new Error(`README.md changelog: month ${match[2]} in "${line.trim()}"`);
      entry = { tag: `v${match[1]}.${match[2]}.${serial}`, npm: `${year}.${month}.${serial}`, key: [year, month, serial], notes: [] };
      entries.push(entry);
    } else if (NOTE.test(line) && entry) {
      entry.notes.push(line.replace(/^ {2}/, ""));
    }
  }
  if (entries.length === 0) throw new Error("README.md changelog: no '* vYYYY.MM.N' entry");
  entries.slice(1).forEach((entry, index) => {
    if (compare(entries[index].key, entry.key) <= 0) throw new Error(`README.md changelog: ${entries[index].tag} must be newer than ${entry.tag} below it`);
  });
  return entries;
}

function compare(a, b) {
  return a[0] - b[0] || a[1] - b[1] || a[2] - b[2];
}

function current() {
  return parseChangelog(fs.readFileSync(README, "utf8"))[0];
}

function write() {
  const { tag } = current();
  const source = `// Generated by scripts/changelog.mjs from the README changelog. Do not edit.\nexport default "${tag.slice(1)}";\n`;
  if (fs.existsSync(MODULE) && fs.readFileSync(MODULE, "utf8") === source) return;
  fs.writeFileSync(MODULE, source);
  console.log(`${path.relative(ROOT, MODULE)}: ${tag}`);
}

// Released versions: the vYYYY.MM.N tags on origin.
function releasedTags() {
  const refs = execFileSync("git", ["ls-remote", "--tags", "origin"], { cwd: ROOT, encoding: "utf8" });
  return refs
    .split("\n")
    .map((line) => TAG.exec(line.split("\t")[1] || ""))
    .filter(Boolean)
    .map((match) => ({ tag: `v${match[1]}.${match[2]}.${match[3]}`, key: match.slice(1).map(Number) }));
}

function github() {
  const entry = current();
  const released = releasedTags();
  const release = !released.some(({ tag }) => tag === entry.tag);
  if (release) {
    const newer = released.find(({ key }) => compare(key, entry.key) > 0);
    if (newer) throw new Error(`${entry.tag} is older than the released ${newer.tag}; add a newer changelog entry`);
  }
  console.error(`${PACKAGE}: ${entry.tag} ${release ? "is new: release" : "is released: nothing to do"}`);
  const delimiter = `NOTES_${Date.now()}`;
  console.log(`release=${release}`);
  console.log(`tag=${entry.tag}`);
  console.log(`version=${entry.npm}`);
  console.log(`notes<<${delimiter}\n${entry.notes.join("\n")}\n${delimiter}`);
}

const mode = process.argv[2];
if (mode === "--write") write();
else if (mode === "--github") github();
else {
  console.error("usage: node scripts/changelog.mjs --write | --github");
  process.exit(2);
}
